### ISSUE TITLE
Store guild-id,calender token in db

### ISSUE THREAD

**Issue by sdf010** [saltyarchons/discord-easy-cal#19]
Check if previous token exist in db and override after asking user to acknowledge

**Comment by sdf010** [comment]
@NotARealTree can you confirm that the put id is meant to be the guild id. we may need a separate index for sessions tokens then as theses only live for a  short while before refresh and we should not be refreshing them until they expire.

**Comment by f-doot** [comment]
It probably makes sense to have a seperate index for tokens anyways, happy to implement that if needed.
