### ISSUE TITLE
error when attempting to set auth token

### ISSUE THREAD

**Issue by sdf010** [saltyarchons/discord-easy-cal#33]
Error:
/app/src/http/server.js:21
                 bot.services.database.putCalendar({
                              ^

 TypeError: Cannot read property 'database' of undefined
     at Server.http.createServer (/app/src/http/server.js:21:30)
     at emitTwo (events.js:126:13)
     at Server.emit (events.js:214:7)
     at parserOnIncoming (_http_server.js:602:12)
     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)

steps to reproduce:
1) visit http://localhost:8080/easyCalAuth?state=3&code=4

**Comment by sdf010** [comment]
@lexwebb as everything is defined in app/bot any way we can simply do:

```` diff
-                 bot.services.database.putCalendar({
+                bot.app.services.database.putCalendar({
````

However in `src/serviceBase.js` we have most of the app variables set as serviceBase variables

```javascript
    constructor(app) {
        this.app = app;
        this.logger = app.logger;
        this.config = app.config;
        this.auth = app.auth;
    }
```

Is there a reason for this?

**Comment by lexwebb** [comment]
There is no reason

**Comment by lexwebb** [comment]
Feel free to refactor that part. It was slightly rushed
